// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ahidbwxaxyxcdhardoyt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFoaWRid3hheHl4Y2RoYXJkb3l0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyODU4NDEsImV4cCI6MjA3MDg2MTg0MX0.EQHHU1zr803Meag0-PycTnFEVqj8-b85Xd_pzZ8WvOE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});